# Generated by Django 4.2.1 on 2023-05-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_mealcategory_mainmealcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarymealcategory',
            name='main_categories',
        ),
        migrations.AddField(
            model_name='secondarymealcategory',
            name='main_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viewer.mainmealcategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(to='viewer.secondarymealcategory'),
        ),
    ]
