# Generated by Django 4.2.1 on 2023-05-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_secondarymealcategory_main_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='recipe_text',
        ),
    ]
