# Generated by Django 4.2.1 on 2023-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_remove_meal_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='picture',
            field=models.ImageField(blank=True, upload_to='viewer/static/images/'),
        ),
        migrations.AddField(
            model_name='mainmealcategory',
            name='picture',
            field=models.ImageField(blank=True, upload_to='viewer/static/images/'),
        ),
        migrations.AddField(
            model_name='secondarymealcategory',
            name='picture',
            field=models.ImageField(blank=True, upload_to='viewer/static/images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='picture',
            field=models.ImageField(blank=True, upload_to='viewer/static/images/'),
        ),
    ]
